[2023-08-13T15:14:25.834+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_dag.tune_task manual__2023-08-13T15:14:24.131529+00:00 [queued]>
[2023-08-13T15:14:25.837+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_dag.tune_task manual__2023-08-13T15:14:24.131529+00:00 [queued]>
[2023-08-13T15:14:25.837+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-08-13T15:14:25.843+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): tune_task> on 2023-08-13 15:14:24.131529+00:00
[2023-08-13T15:14:25.847+0000] {standard_task_runner.py:57} INFO - Started process 90 to run task
[2023-08-13T15:14:25.849+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tune_dag', 'tune_task', 'manual__2023-08-13T15:14:24.131529+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/scripts/tune_ml.py', '--cfg-path', '/tmp/tmppbuvmmr9']
[2023-08-13T15:14:25.850+0000] {standard_task_runner.py:85} INFO - Job 179: Subtask tune_task
[2023-08-13T15:14:25.868+0000] {task_command.py:410} INFO - Running <TaskInstance: tune_dag.tune_task manual__2023-08-13T15:14:24.131529+00:00 [running]> on host 7a4e6bd18795
[2023-08-13T15:14:25.899+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thanhdong18891@gmail.com' AIRFLOW_CTX_DAG_OWNER='DongNT17' AIRFLOW_CTX_DAG_ID='tune_dag' AIRFLOW_CTX_TASK_ID='tune_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-13T15:14:24.131529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-13T15:14:24.131529+00:00'
[2023-08-13T15:14:25.900+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-13T15:14:25.900+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' bash -i /opt/***/dags/scripts/train.sh ']
[2023-08-13T15:14:25.908+0000] {subprocess.py:86} INFO - Output:
[2023-08-13T15:14:25.910+0000] {subprocess.py:93} INFO - bash: cannot set terminal process group (-1): Inappropriate ioctl for device
[2023-08-13T15:14:25.910+0000] {subprocess.py:93} INFO - bash: no job control in this shell
[2023-08-13T15:14:26.257+0000] {subprocess.py:93} INFO - bash: cd: /home/***/dog_cat_mlops: No such file or directory
[2023-08-13T15:14:26.257+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-13T15:14:26.262+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-13T15:14:26.264+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_dag, task_id=tune_task, execution_date=20230813T151424, start_date=20230813T151425, end_date=20230813T151426
[2023-08-13T15:14:26.269+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 179 for task tune_task (Bash command failed. The command returned a non-zero exit code 1.; 90)
[2023-08-13T15:14:26.301+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-13T15:14:26.315+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
