[2023-08-12T04:49:39.577+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_dag.tune_task manual__2023-08-12T04:47:49.800785+00:00 [queued]>
[2023-08-12T04:49:39.581+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_dag.tune_task manual__2023-08-12T04:47:49.800785+00:00 [queued]>
[2023-08-12T04:49:39.581+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-08-12T04:49:39.586+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): tune_task> on 2023-08-12 04:47:49.800785+00:00
[2023-08-12T04:49:39.591+0000] {standard_task_runner.py:57} INFO - Started process 240 to run task
[2023-08-12T04:49:39.592+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tune_dag', 'tune_task', 'manual__2023-08-12T04:47:49.800785+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/scripts/tune_ml.py', '--cfg-path', '/tmp/tmp1c9e7axa']
[2023-08-12T04:49:39.593+0000] {standard_task_runner.py:85} INFO - Job 76: Subtask tune_task
[2023-08-12T04:49:39.610+0000] {task_command.py:410} INFO - Running <TaskInstance: tune_dag.tune_task manual__2023-08-12T04:47:49.800785+00:00 [running]> on host 67c44e1a363a
[2023-08-12T04:49:39.639+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thanhdong18891@gmail.com' AIRFLOW_CTX_DAG_OWNER='DongNT17' AIRFLOW_CTX_DAG_ID='tune_dag' AIRFLOW_CTX_TASK_ID='tune_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-12T04:47:49.800785+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-12T04:47:49.800785+00:00'
[2023-08-12T04:49:39.640+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-12T04:49:39.641+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' bash -i /opt/***/dags/scripts/train.sh ']
[2023-08-12T04:49:39.649+0000] {subprocess.py:86} INFO - Output:
[2023-08-12T04:49:39.651+0000] {subprocess.py:93} INFO - bash: cannot set terminal process group (-1): Inappropriate ioctl for device
[2023-08-12T04:49:39.651+0000] {subprocess.py:93} INFO - bash: no job control in this shell
[2023-08-12T04:49:40.696+0000] {subprocess.py:93} INFO - # conda environments:
[2023-08-12T04:49:40.697+0000] {subprocess.py:93} INFO - #
[2023-08-12T04:49:40.705+0000] {subprocess.py:93} INFO - base                     /home/***/conda
[2023-08-12T04:49:40.705+0000] {subprocess.py:93} INFO - training_env          *  /home/***/conda/envs/training_env
[2023-08-12T04:49:40.705+0000] {subprocess.py:93} INFO - 
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -   File "/home/***/dog_cat_mlops/./ml/train.py", line 17, in <module>
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -     model = models.resnet50().cuda()
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -             ^^^^^^^^^^^^^^^^^^^^^^^^
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -   File "/home/***/conda/envs/training_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 905, in cuda
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -     return self._apply(lambda t: t.cuda(device))
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -   File "/home/***/conda/envs/training_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -     module._apply(fn)
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -   File "/home/***/conda/envs/training_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -     param_applied = fn(param)
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -                     ^^^^^^^^^
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -   File "/home/***/conda/envs/training_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -     return self._apply(lambda t: t.cuda(device))
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -                                  ^^^^^^^^^^^^^^
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -   File "/home/***/conda/envs/training_env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO -     raise AssertionError("Torch not compiled with CUDA enabled")
[2023-08-12T04:49:41.679+0000] {subprocess.py:93} INFO - AssertionError: Torch not compiled with CUDA enabled
[2023-08-12T04:49:41.817+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-12T04:49:41.823+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-12T04:49:41.824+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_dag, task_id=tune_task, execution_date=20230812T044749, start_date=20230812T044939, end_date=20230812T044941
[2023-08-12T04:49:41.838+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 76 for task tune_task (Bash command failed. The command returned a non-zero exit code 1.; 240)
[2023-08-12T04:49:41.848+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-12T04:49:41.857+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
