[2023-08-13T14:56:21.286+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_dag.tune_task manual__2023-08-13T14:56:19.200243+00:00 [queued]>
[2023-08-13T14:56:21.289+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_dag.tune_task manual__2023-08-13T14:56:19.200243+00:00 [queued]>
[2023-08-13T14:56:21.289+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-08-13T14:56:21.295+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): tune_task> on 2023-08-13 14:56:19.200243+00:00
[2023-08-13T14:56:21.299+0000] {standard_task_runner.py:57} INFO - Started process 91 to run task
[2023-08-13T14:56:21.301+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tune_dag', 'tune_task', 'manual__2023-08-13T14:56:19.200243+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/scripts/tune_ml.py', '--cfg-path', '/tmp/tmpb1ec1u3t']
[2023-08-13T14:56:21.302+0000] {standard_task_runner.py:85} INFO - Job 172: Subtask tune_task
[2023-08-13T14:56:21.319+0000] {task_command.py:410} INFO - Running <TaskInstance: tune_dag.tune_task manual__2023-08-13T14:56:19.200243+00:00 [running]> on host a6a40f1038a0
[2023-08-13T14:56:21.352+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thanhdong18891@gmail.com' AIRFLOW_CTX_DAG_OWNER='DongNT17' AIRFLOW_CTX_DAG_ID='tune_dag' AIRFLOW_CTX_TASK_ID='tune_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-13T14:56:19.200243+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-13T14:56:19.200243+00:00'
[2023-08-13T14:56:21.353+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-13T14:56:21.353+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' bash -i /opt/***/dags/scripts/train.sh ']
[2023-08-13T14:56:21.360+0000] {subprocess.py:86} INFO - Output:
[2023-08-13T14:56:21.362+0000] {subprocess.py:93} INFO - bash: cannot set terminal process group (-1): Inappropriate ioctl for device
[2023-08-13T14:56:21.362+0000] {subprocess.py:93} INFO - bash: no job control in this shell
[2023-08-13T14:56:21.711+0000] {subprocess.py:93} INFO - bash: cd: /home/***/dog_cat_mlops: No such file or directory
[2023-08-13T14:56:21.711+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-13T14:56:21.717+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-13T14:56:21.719+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_dag, task_id=tune_task, execution_date=20230813T145619, start_date=20230813T145621, end_date=20230813T145621
[2023-08-13T14:56:21.725+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 172 for task tune_task (Bash command failed. The command returned a non-zero exit code 1.; 91)
[2023-08-13T14:56:21.753+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-13T14:56:21.793+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
